name: Castel-Plugin
version: '${project.version}'
main: fr.krishenk.castel.CastelPlugin
api-version: 1.16
softdepend: [Essentials, Vault, PlaceholderAPI, WorldEdit, WorldGuard]
#softdepend: [ SaberFactions, Factions ]